version: latest

services:
  selenium-hub:
    image: selenium/hub
    shm_size: 2gb
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
    
  chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - grid

networks:
  grid:
    name: grid
    driver: bridge